# Generated by Django 4.2.3 on 2023-08-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0002_categorymodel_productmodel_subcategorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.categorymodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='SubCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.subcategorymodel'),
        ),
    ]
