# Generated by Django 4.2.3 on 2023-08-29 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olxApp', '0004_productmodel_product_img1_productmodel_product_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='image/')),
                ('state', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('Join_Date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.buyerdata'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.buyerdata'),
        ),
    ]
