# Generated by Django 4.2.3 on 2023-09-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0007_img_1_img_2_img_3_remove_productmodel_product_img1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img_1',
        ),
        migrations.DeleteModel(
            name='Img_2',
        ),
        migrations.DeleteModel(
            name='Img_3',
        ),
    ]
