# Generated by Django 4.2.3 on 2023-09-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0008_delete_img_1_delete_img_2_delete_img_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='Product_Img',
        ),
        migrations.CreateModel(
            name='Product_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productmodel')),
            ],
        ),
    ]
