# Generated by Django 4.2.3 on 2023-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0009_remove_productmodel_product_img_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Product_Img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
