# Generated by Django 4.2.3 on 2023-09-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0010_productmodel_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Img',
        ),
    ]
