# Generated by Django 4.2.3 on 2023-09-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0011_delete_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='Product_Img',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
