# Generated by Django 4.2.3 on 2023-09-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0013_remove_productmodel_image_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='images',
            field=models.ManyToManyField(to='olxApp.productimage'),
        ),
    ]
