# Generated by Django 4.2.3 on 2023-09-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0014_productimage_delete_uploadedimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productmodel'),
        ),
    ]
