# Generated by Django 4.2.6 on 2023-10-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0016_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdata',
            name='number',
            field=models.IntegerField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='number',
            field=models.IntegerField(max_length=70),
        ),
    ]
