# Generated by Django 4.2.6 on 2023-10-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0017_alter_buyerdata_number_alter_sellerdata_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdata',
            name='country',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='number',
            field=models.IntegerField(max_length=11),
        ),
    ]
