# Generated by Django 4.2.6 on 2023-10-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0018_alter_buyerdata_country_alter_sellerdata_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdata',
            name='country',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='buyerdata',
            name='number',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='number',
            field=models.CharField(max_length=70),
        ),
    ]
