# Generated by Django 4.2.6 on 2023-10-25 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0021_remove_productmodel_image_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Join_Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
