# Generated by Django 4.2.6 on 2023-11-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0023_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productmodel'),
        ),
    ]
