# Generated by Django 4.2.6 on 2023-11-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0024_userlocation_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='Product',
            new_name='Prod',
        ),
    ]
