# Generated by Django 4.2.6 on 2023-11-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0025_rename_product_userlocation_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.sellerdata'),
        ),
    ]
