# Generated by Django 4.2.6 on 2023-11-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0027_cartmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('companyname', models.CharField(max_length=70)),
                ('housenumber', models.CharField(max_length=70)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=70)),
                ('order_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('cardname', models.CharField(max_length=70)),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
                ('securitycode', models.IntegerField()),
                ('order_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
