# Generated by Django 4.2.6 on 2023-11-16 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olxApp', '0028_billingdata_paymentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdata',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.buyerdata'),
        ),
        migrations.AddField(
            model_name='billingdata',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productmodel'),
        ),
        migrations.AddField(
            model_name='billingdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
