# Generated by Django 4.2.6 on 2023-11-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0030_remove_billingdata_product_billingdata_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdata',
            old_name='pincode',
            new_name='cardnumber',
        ),
    ]
