# Generated by Django 4.2.6 on 2023-11-16 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olxApp', '0031_rename_pincode_paymentdata_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.buyerdata'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.cartmodel'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
