# Generated by Django 4.2.6 on 2023-11-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0032_paymentdata_buyer_paymentdata_cart_paymentdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdata',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productmodel'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productmodel'),
        ),
    ]
