# Generated by Django 4.2.6 on 2023-11-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0035_rename_is_approved_productmodel_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdata',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productimage'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productimage'),
        ),
    ]
