# Generated by Django 4.2.6 on 2023-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0036_billingdata_image_paymentdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
