# Generated by Django 4.2.6 on 2023-11-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0038_reviewdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdata',
            name='order',
        ),
        migrations.AddField(
            model_name='reviewdata',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.billingdata'),
        ),
        migrations.AddField(
            model_name='reviewdata',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.buyerdata'),
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
