# Generated by Django 4.2.6 on 2023-11-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0039_remove_reviewdata_order_reviewdata_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdata',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.productimage'),
        ),
    ]
