# Generated by Django 4.2.6 on 2023-11-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0042_paymentdata_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
