# Generated by Django 4.2.6 on 2023-11-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0043_productmodel_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdata',
            name='address',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='address',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
