# Generated by Django 4.2.6 on 2023-11-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0045_alter_buyerdata_country_alter_buyerdata_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdata',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='paymentdata',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='reviewdata',
            name='buyer',
        ),
        migrations.AddField(
            model_name='billingdata',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.sellerdata'),
        ),
        migrations.AddField(
            model_name='reviewdata',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.sellerdata'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.sellerdata'),
        ),
        migrations.DeleteModel(
            name='BuyerData',
        ),
    ]
