# Generated by Django 4.2.6 on 2023-11-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0046_remove_billingdata_buyer_remove_chatmessage_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdata',
            name='user',
        ),
    ]
