# Generated by Django 4.2.6 on 2023-11-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0049_remove_productmodel_user_remove_reviewdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdata',
            name='billing',
        ),
        migrations.AddField(
            model_name='reviewdata',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxApp.paymentdata'),
        ),
    ]
