# Generated by Django 4.2.6 on 2023-11-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxApp', '0050_remove_reviewdata_billing_reviewdata_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdata',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='paymentdata',
            name='image',
        ),
        migrations.RemoveField(
            model_name='paymentdata',
            name='product',
        ),
        migrations.RemoveField(
            model_name='paymentdata',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='reviewdata',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviewdata',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='reviewdata',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewdata',
            name='seller',
        ),
        migrations.DeleteModel(
            name='BillingData',
        ),
        migrations.DeleteModel(
            name='PaymentData',
        ),
        migrations.DeleteModel(
            name='ReviewData',
        ),
    ]
